# Generated by Django 6.0.3 on 2026-03-17 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_tr', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(default='', help_text='Unique key e.g. coal-industrial', max_length=100)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct'), ('scope2', 'Scope 2 - Energy Indirect'), ('scope3', 'Scope 3 - Other Indirect')], max_length=10)),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('fugitive_emissions', 'Fugitive Emissions'), ('electricity', 'Electricity'), ('steam_heat', 'Steam & Heat'), ('purchased_goods', 'Purchased Goods & Services'), ('capital_goods', 'Capital Goods'), ('fuel_energy', 'Fuel & Energy Related'), ('upstream_transport', 'Upstream Transportation'), ('waste', 'Waste Generated'), ('business_travel', 'Business Travel'), ('employee_commuting', 'Employee Commuting'), ('upstream_leased', 'Upstream Leased Assets'), ('downstream_transport', 'Downstream Transportation'), ('end_of_life', 'End-of-Life Treatment'), ('franchises', 'Franchises'), ('investments', 'Investments'), ('water', 'Water'), ('custom', 'Custom')], max_length=50)),
                ('country', models.CharField(choices=[('global', 'Global'), ('turkey', 'Turkey')], default='global', max_length=10)),
                ('unit', models.CharField(choices=[('liters', 'Litres'), ('kg', 'Kilogram'), ('tonne', 'Tonne'), ('kwh', 'kWh'), ('gj', 'GJ'), ('m3', 'm³'), ('m2', 'm²'), ('km', 'Kilometre'), ('pkm', 'Passenger-km'), ('tonne-km', 'Tonne-km'), ('night', 'Night'), ('units', 'Unit'), ('packages', 'Packages'), ('usd', 'USD'), ('franchises', 'Franchises')], max_length=20)),
                ('factor_kg_co2e', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=14)),
                ('source', models.CharField(choices=[('defra_2024', 'Defra/DESNZ 2024'), ('ipcc_2006', 'IPCC 2006'), ('ipcc_2019', 'IPCC 2019 + AR6 GWP'), ('turkey_grid', 'Turkey Grid/National'), ('atom_kablo', 'ATOM KABLO ISO 14064-1'), ('icao', 'ICAO'), ('turkey_fleet', 'Turkey Fleet'), ('generic', 'Generic/Estimated'), ('custom', 'Custom')], default='defra_2024', max_length=20)),
                ('reference', models.TextField(blank=True, help_text='Source reference text')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['scope', 'category', 'name'],
                'unique_together': {('slug', 'country')},
            },
        ),
        migrations.CreateModel(
            name='EmissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('calculated_co2e_kg', models.DecimalField(decimal_places=4, editable=False, max_digits=16)),
                ('description', models.TextField(blank=True)),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_entries', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.emissionfactor')),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReductionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_year', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('base_emissions_kg', models.DecimalField(decimal_places=4, max_digits=14)),
                ('target_reduction_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('off_track', 'Off Track'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='on_track', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reduction_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
