# Generated by Django 6.0.3 on 2026-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='is_default',
            field=models.BooleanField(default=True, help_text='Default factor for this slug+country+category'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='year',
            field=models.IntegerField(default=2024, help_text='Factor reference year (hidden from user)'),
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('slug', 'country', 'year')},
        ),
    ]
