# Generated by Django 6.0.3 on 2026-04-06 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_alter_emissionfactor_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct'), ('scope2', 'Scope 2 - Energy Indirect'), ('scope3', 'Scope 3 - Other Indirect')], max_length=10)),
                ('category_name', models.CharField(help_text='User-described category', max_length=255)),
                ('source_name', models.CharField(help_text='User-described emission source', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the emission activity')),
                ('unit', models.CharField(help_text='Unit of measurement (e.g. liters, kg, kWh)', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Amount consumed', max_digits=14)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('facility', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('approved_factor_kg_co2e', models.DecimalField(blank=True, decimal_places=6, help_text='Factor assigned by admin after review', max_digits=14, null=True)),
                ('calculated_co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='Calculated after admin approval', max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_entry', models.ForeignKey(blank=True, help_text='EmissionEntry created after approval', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_emission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
