# Generated by Django 6.0.3 on 2026-04-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_customemissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionentry',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Upload invoice, receipt, or meter reading', null=True, upload_to='proofs/%Y/%m/'),
        ),
    ]
