# Generated by Django 6.0.3 on 2026-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0004_emissionentry_proof_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionentry',
            name='factor_source_snapshot',
            field=models.CharField(blank=True, help_text='Factor source/reference at time of entry', max_length=255),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='factor_value_snapshot',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Factor value at time of entry creation', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('draft', 'Draft')], default='submitted', max_length=20),
        ),
    ]
