# Generated by Django 6.0.3 on 2026-04-09 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_facility'),
        ('emissions', '0005_emissionentry_factor_source_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemissionrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_emission_requests', to='companies.company'),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_entries', to='companies.company'),
        ),
        migrations.AddField(
            model_name='reductiontarget',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reduction_targets', to='companies.company'),
        ),
    ]
