# Generated by Django 6.0.3 on 2026-04-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_backfill_memberships'),
        ('emissions', '0006_customemissionrequest_company_emissionentry_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemissionrequest',
            name='facility_ref',
            field=models.ForeignKey(blank=True, help_text='Structured facility reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_emission_requests', to='companies.facility'),
        ),
        migrations.AddField(
            model_name='emissionentry',
            name='facility_ref',
            field=models.ForeignKey(blank=True, help_text='Structured facility reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_entries', to='companies.facility'),
        ),
        migrations.AlterField(
            model_name='customemissionrequest',
            name='facility',
            field=models.CharField(blank=True, help_text='Legacy text field', max_length=255),
        ),
        migrations.AlterField(
            model_name='emissionentry',
            name='facility',
            field=models.CharField(blank=True, help_text='Legacy text field', max_length=255),
        ),
    ]
