# Generated by Django 6.0.3 on 2026-04-15 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_company_user'),
        ('emissions', '0008_emissionentry_approved_at_emissionentry_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customemissionrequest',
            name='facility_ref',
        ),
        migrations.RemoveField(
            model_name='emissionentry',
            name='facility_ref',
        ),
        migrations.AlterField(
            model_name='customemissionrequest',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Structured facility reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_emission_requests', to='companies.facility'),
        ),
        migrations.AlterField(
            model_name='emissionentry',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Structured facility reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_entries', to='companies.facility'),
        ),
    ]
