# Generated by Django 6.0.3 on 2026-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0009_facility_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionentry',
            name='rejected_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
    ]
