# Generated by Django 5.0.6 on 2026-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0010_emissionentry_rejected_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='category',
            field=models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('fugitive_emissions', 'Fugitive Emissions'), ('electricity', 'Electricity'), ('steam_heat', 'Steam & Heat'), ('purchased_goods', 'Purchased Goods & Services'), ('capital_goods', 'Capital Goods'), ('fuel_energy', 'Fuel & Energy Related'), ('upstream_transport', 'Upstream Transportation'), ('waste', 'Waste Generated'), ('business_travel', 'Business Travel'), ('employee_commuting', 'Employee Commuting'), ('upstream_leased', 'Upstream Leased Assets'), ('downstream_transport', 'Downstream Transportation'), ('processing_sold', 'Processing of Sold Products'), ('use_of_sold', 'Use of Sold Products'), ('end_of_life', 'End-of-Life Treatment'), ('franchises', 'Franchises'), ('investments', 'Investments'), ('water', 'Water'), ('custom', 'Custom')], max_length=50),
        ),
    ]
