# Generated by Django 5.1.15 on 2026-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0012_fix_flight_factors_scope3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='source',
            field=models.CharField(choices=[('defra_2024', 'Defra/DESNZ 2024'), ('ipcc_2006', 'IPCC 2006'), ('ipcc_2019', 'IPCC 2019 + AR6 GWP'), ('turkey_grid', 'Turkey Grid/National'), ('atom_kablo', 'Turkey ISO 14064-1 verified inventory'), ('icao', 'ICAO'), ('turkey_fleet', 'Turkey Fleet'), ('generic', 'Generic/Estimated'), ('custom', 'Custom')], default='defra_2024', max_length=20),
        ),
    ]
