# Generated by Django 5.1.15 on 2026-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0013_alter_emissionfactor_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionfactor',
            name='factor_ch4_kg_co2e',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit attributable to CH4', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='factor_co2_kg_co2e',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit attributable to CO2', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='factor_hfc_kg_co2e',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit attributable to HFCs (HCFCs reported here too)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='factor_n2o_kg_co2e',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit attributable to N2O', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='factor_pfc_kg_co2e',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit attributable to PFCs', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='factor_sf6_kg_co2e',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='kg CO2e per unit attributable to SF6', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='gas_split_basis',
            field=models.CharField(blank=True, choices=[('published', 'Published by the factor source'), ('apportioned', 'Apportioned from published default gas ratios'), ('single_gas', 'Single-gas source — whole factor is one gas')], help_text='How the per-gas breakdown was arrived at. Required when any gas field is set.', max_length=20),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='gas_split_reference',
            field=models.TextField(blank=True, help_text='Citation for the per-gas breakdown, e.g. the IPCC table the ratios come from'),
        ),
    ]
