# Generated by Django 5.1.15 on 2026-10-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emissions", "0018_public_transport_scope3"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionentry",
            name="calc_detail",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
