# Generated by Django 5.0.6 on 2026-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_attachment_to_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ui',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
