# Generated by Django 5.1.15 on 2026-10-09 16:40

import django.db.models.deletion
from django.db import migrations, models


def assign_company(apps, schema_editor):
    """Existing chats go to the company the user was working in (else their
    first active membership) — the one their answers were drawn from."""
    ChatSession = apps.get_model('chat', 'ChatSession')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    CompanyMembership = apps.get_model('companies', 'CompanyMembership')
    for user_id in ChatSession.objects.filter(company__isnull=True).values_list('user_id', flat=True).distinct():
        profile = UserProfile.objects.filter(user_id=user_id).first()
        company_id = getattr(profile, 'active_company_id', None)
        if not company_id:
            m = CompanyMembership.objects.filter(user_id=user_id, is_active=True).order_by('id').first()
            company_id = m.company_id if m else None
        if company_id:
            ChatSession.objects.filter(user_id=user_id, company__isnull=True).update(company_id=company_id)


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_chatmessage_ui_chatsession_state"),
        ("companies", "0008_company_certificates_and_more"),
        ("accounts", "0014_notification_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to="companies.company",
            ),
        ),
        migrations.RunPython(assign_company, migrations.RunPython.noop),
    ]
