# Generated by Django 5.0.6 on 2026-05-04 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyinvite'),
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('current_step', models.CharField(default='A1', max_length=10)),
                ('reporting_year', models.IntegerField(blank=True, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100)),
                ('purposes', models.JSONField(default=list)),
                ('legal_framework', models.CharField(blank=True, max_length=200)),
                ('voluntary_framework', models.CharField(blank=True, max_length=200)),
                ('has_previous_report', models.BooleanField(null=True)),
                ('baseline_year', models.IntegerField(blank=True, null=True)),
                ('has_subsidiaries', models.BooleanField(null=True)),
                ('has_international', models.BooleanField(null=True)),
                ('has_jv_franchise', models.BooleanField(null=True)),
                ('ef_database', models.CharField(blank=True, choices=[('DEFRA', 'DEFRA 2023'), ('DEFRA_TUIK', 'DEFRA + TÜİK'), ('IPCC_AR6', 'IPCC AR6 2021'), ('EPA', 'EPA'), ('custom', 'Custom')], max_length=20)),
                ('ef_custom_source', models.CharField(blank=True, max_length=200)),
                ('ef_custom_year', models.IntegerField(blank=True, null=True)),
                ('scope2_method', models.CharField(default='location_based', max_length=20)),
                ('boundary_approach', models.CharField(blank=True, choices=[('operational_control', 'Operational Control'), ('financial_control', 'Financial Control'), ('equity_share', 'Equity Share')], max_length=30)),
                ('scope3_approach', models.CharField(blank=True, choices=[('materiality', 'Materiality Based'), ('full', 'Full 15 Categories')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_reports', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reporting_year')},
            },
        ),
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=10)),
                ('assumption_type', models.CharField(choices=[('A', 'Data Gap'), ('B', 'Methodology Choice'), ('C', 'Boundary Decision')], max_length=1)),
                ('auto_text', models.TextField()),
                ('user_approved', models.BooleanField(default=False)),
                ('impact_direction', models.CharField(blank=True, choices=[('high', 'High Estimate'), ('low', 'Low Estimate'), ('uncertain', 'Uncertain'), ('neutral', 'No Impact')], max_length=10)),
                ('improvement_path', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='questionnaire.carbonreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=10)),
                ('answer', models.JSONField(default=dict)),
                ('is_skipped', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='questionnaire.carbonreport')),
            ],
            options={
                'ordering': ['completed_at'],
                'unique_together': {('report', 'step_id')},
            },
        ),
    ]
