# Generated by Django 6.0.3 on 2026-05-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_carbonreport_assumption_reportstep'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carbonreport',
            unique_together=set(),
        ),
    ]
