# Generated by Django 5.0.6 on 2026-05-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alter_carbonreport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonreport',
            name='ef_database',
            field=models.CharField(blank=True, choices=[('DEFRA', 'DEFRA 2023'), ('DEFRA_TUIK', 'DEFRA + TÜİK'), ('IPCC_AR6', 'IPCC AR6 2021'), ('EPA', 'EPA'), ('ecoinvent', 'ecoinvent'), ('other', 'Other / Country-specific'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carbonreport',
            name='scope3_approach',
            field=models.CharField(blank=True, choices=[('materiality', 'Materiality Based'), ('full_15', 'Full 15 Categories'), ('exclude', 'Scope 1 & 2 Only')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questionnairesession',
            name='current_question',
            field=models.CharField(default='A1', max_length=20),
        ),
    ]
