# Generated by Django 6.0.3 on 2026-08-06 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_carbonreport_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumption',
            name='step_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportstep',
            name='step_id',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='AdvisorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(help_text="e.g. '3A-EF', 'K3C5-1'", max_length=50)),
                ('field_id', models.CharField(help_text="Question Map field_id, e.g. 'ef.ef_3a'", max_length=100)),
                ('reason_code', models.CharField(help_text="e.g. 'custom_ef_override', 'rfi_applied'", max_length=50)),
                ('trigger_category', models.CharField(help_text='Veri Girişi / Metodoloji / Kapsam / Belge / Tutarsızlık', max_length=30)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('medium_high', 'Medium-High'), ('high', 'High'), ('critical', 'Critical'), ('warning', 'Warning'), ('positive', 'Positive')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable context/snapshot of the triggering answer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_approvals', to='questionnaire.carbonreport')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('report', 'question_id', 'reason_code')},
            },
        ),
    ]
