# Generated by Django 5.1.15 on 2026-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_alter_assumption_step_id_alter_reportstep_step_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonreport',
            name='current_step',
            field=models.CharField(default='A1', max_length=50),
        ),
    ]
