# Generated by Django 5.1.15 on 2026-09-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaire", "0007_alter_carbonreport_current_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbonreport",
            name="client_progress",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
