# Generated by Django 6.0.3 on 2026-04-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('entry_created', 'Emission Entry Created'), ('entry_deleted', 'Emission Entry Deleted'), ('entry_updated', 'Emission Entry Updated'), ('custom_submitted', 'Custom Request Submitted'), ('custom_approved', 'Custom Request Approved'), ('custom_rejected', 'Custom Request Rejected'), ('report_generated', 'Report Generated'), ('password_changed', 'Password Changed'), ('login', 'Login')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
