# Generated by Django 6.0.3 on 2026-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_id',
            field=models.CharField(blank=True, help_text='PK of the target object', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(blank=True, help_text='e.g. EmissionEntry, CustomRequest', max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('entry_created', 'Emission Entry Created'), ('entry_deleted', 'Emission Entry Deleted'), ('entry_updated', 'Emission Entry Updated'), ('custom_submitted', 'Custom Request Submitted'), ('custom_approved', 'Custom Request Approved'), ('custom_rejected', 'Custom Request Rejected'), ('report_generated', 'Report Generated'), ('password_changed', 'Password Changed'), ('login', 'Login')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
