# Generated by Django 6.0.3 on 2026-04-09 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activitylog_metadata_activitylog_target_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('data_entry', 'Data Entry'), ('auditor', 'Auditor (Read-Only)')], default='data_entry', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='accounts_ac_user_id_3418de_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='accounts_ac_action_2bf4c4_idx'),
        ),
    ]
