# Generated by Django 6.0.3 on 2026-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], default='tr', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_approvals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_system',
            field=models.BooleanField(default=True),
        ),
    ]
