# Generated by Django 5.0.6 on 2026-07-12 11:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_totpdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='code',
            field=models.CharField(default=accounts.models._generate_verification_code, max_length=6),
        ),
    ]
