# Generated by Django 5.1.15 on 2026-08-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_emailverificationtoken_attempts_and_more'),
        ('companies', '0007_companyinvite_expires_at_and_invited_by_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.company'),
        ),
    ]
