# Generated by Django 5.1.15 on 2026-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_userprofile_active_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(max_length=5000)),
                ("language", models.CharField(blank=True, max_length=5)),
                ("email_sent", models.BooleanField(default=False)),
                ("handled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("custom_approved", "Custom Request Approved"),
                    ("custom_rejected", "Custom Request Rejected"),
                    ("target_alert", "Target Alert"),
                    ("report_ready", "Report Ready"),
                    ("entry_submitted", "Entry Awaiting Approval"),
                    ("entry_approved", "Entry Approved"),
                    ("entry_rejected", "Entry Rejected"),
                    ("system", "System Message"),
                ],
                max_length=20,
            ),
        ),
    ]
