# Generated by Django 5.1.15 on 2026-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_clear_company_name_as_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("entry_created", "Emission Entry Created"),
                    ("entry_deleted", "Emission Entry Deleted"),
                    ("entry_updated", "Emission Entry Updated"),
                    ("entry_approved", "Emission Entry Approved"),
                    ("entry_rejected", "Emission Entry Rejected"),
                    ("custom_submitted", "Custom Request Submitted"),
                    ("custom_approved", "Custom Request Approved"),
                    ("custom_rejected", "Custom Request Rejected"),
                    ("report_generated", "Report Generated"),
                    ("password_changed", "Password Changed"),
                    ("login", "Login"),
                    ("account_deleted", "Account Deleted"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
