# Generated by Django 5.1.15 on 2026-09-29 21:42

import django.db.models.deletion
from datetime import timedelta

from django.db import migrations, models

WINDOW = timedelta(seconds=60)


def backfill_company(apps, schema_editor):
    """Give existing entry/custom-request notices their company.

    A user in one company: that company. A user in several: the company of
    the entry (or custom request) created/reviewed within a minute of the
    notice, when exactly one of their companies has one. Otherwise the notice
    stays company-less and keeps showing everywhere, as before."""
    Notification = apps.get_model('accounts', 'Notification')
    Membership = apps.get_model('companies', 'CompanyMembership')
    EmissionEntry = apps.get_model('emissions', 'EmissionEntry')
    CustomRequest = apps.get_model('emissions', 'CustomEmissionRequest')
    companies_of = {}
    for user_id, company_id in Membership.objects.values_list('user_id', 'company_id'):
        companies_of.setdefault(user_id, set()).add(company_id)
    for n in Notification.objects.filter(company__isnull=True).exclude(notification_type='system'):
        mine = companies_of.get(n.user_id, set())
        if len(mine) == 1:
            company_id = next(iter(mine))
        elif mine:
            lo, hi = n.created_at - WINDOW, n.created_at + WINDOW
            if n.notification_type.startswith('custom_'):
                found = CustomRequest.objects.filter(company_id__in=mine, updated_at__range=(lo, hi))
            elif n.notification_type == 'entry_submitted':
                found = EmissionEntry.objects.filter(company_id__in=mine, created_at__range=(lo, hi))
            else:
                found = EmissionEntry.objects.filter(company_id__in=mine, updated_at__range=(lo, hi))
            hits = set(found.values_list('company_id', flat=True))
            if len(hits) != 1:
                continue
            company_id = hits.pop()
        else:
            continue
        Notification.objects.filter(pk=n.pk).update(company_id=company_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_activitylog_action"),
        ("companies", "0008_company_certificates_and_more"),
        ("emissions", "0018_public_transport_scope3"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="companies.company",
            ),
        ),
        migrations.RunPython(backfill_company, migrations.RunPython.noop),
    ]
