'use client';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { useLanguage } from '@/lib/i18n/LanguageContext';

export default function TermsPage() {
  const { language } = useLanguage();
  const tr = language === 'tr';

  return (
    <div className="min-h-screen bg-[#F1FCF2] px-4 py-10 sm:px-6">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="mb-8 inline-flex items-center gap-2 text-sm font-bold text-[#072C0E]/50 transition hover:text-[#072C0E]">
          <ArrowLeft className="h-4 w-4" /> {tr ? 'Ana Sayfaya Dön' : 'Back to Home'}
        </Link>

        <div className="rounded-[1.5rem] border border-[#072C0E]/10 bg-white/80 p-6 shadow-[0_8px_30px_rgba(7, 44, 14,0.06)] backdrop-blur-xl sm:p-10">
          <h1 className="text-2xl font-bold tracking-[-0.03em] text-[#072C0E] sm:text-3xl">Terms of Use</h1>
          <p className="mt-2 text-sm text-[#072C0E]/50">Last updated: May 2026</p>

          <div className="mt-8 space-y-6 text-sm leading-7 text-[#072C0E]/70">
            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">1. Acceptance of Terms</h2>
              <p>By accessing and using the Carbonless platform (&quot;Service&quot;), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the Service.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">2. Description of Service</h2>
              <p>Carbonless is a carbon inventory and reporting platform that helps organizations calculate, manage, and report their greenhouse gas emissions in accordance with ISO 14064-1:2018 and the GHG Protocol Corporate Standard.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">3. User Accounts</h2>
              <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate and complete information during registration and to update such information as necessary.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">4. Data Ownership</h2>
              <p>You retain all ownership rights to the data you input into the platform. Carbonless does not claim ownership of your emission data, reports, or any other content you create using the Service.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">5. Acceptable Use</h2>
              <p>You agree not to misuse the Service, including but not limited to: attempting to gain unauthorized access, interfering with other users, or using the platform for any unlawful purpose.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">6. Disclaimer</h2>
              <p>The emission calculations and reports generated by Carbonless are based on the data you provide and publicly available emission factors. The platform does not guarantee the accuracy of third-party emission factors. Reports are not a substitute for professional verification.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">7. Limitation of Liability</h2>
              <p>Carbonless shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount paid by you in the twelve months preceding the claim.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">8. Modifications</h2>
              <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the modified terms.</p>
            </section>

            <section>
              <h2 className="mb-2 text-base font-bold text-[#072C0E]">9. Contact</h2>
              <p>For questions about these Terms, please contact us at <span className="font-bold text-[#2ABD41]">legal@carbonless.info</span></p>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}
