'use client';
import LegalPage from '@/components/legal/LegalPage';

const CONTENT = {
  en: {
    title: 'Terms of Use',
    updated: 'Last updated: May 2026',
    sections: [
      { h: 'Acceptance of Terms', p: 'By accessing and using the Carbonless platform ("Service"), you agree to be bound by these Terms of Use. If you do not agree to these terms, please do not use the Service.' },
      { h: 'Description of Service', p: 'Carbonless is a carbon inventory and reporting platform that helps organizations calculate, manage, and report their greenhouse gas emissions in accordance with ISO 14064-1:2018 and the GHG Protocol Corporate Standard.' },
      { h: 'User Accounts', p: 'You are responsible for maintaining the confidentiality of your account credentials. You agree to provide accurate and complete information during registration and to update such information as necessary.' },
      { h: 'Data Ownership', p: 'You retain all ownership rights to the data you input into the platform. Carbonless does not claim ownership of your emission data, reports, or any other content you create using the Service.' },
      { h: 'Acceptable Use', p: 'You agree not to misuse the Service, including but not limited to: attempting to gain unauthorized access, interfering with other users, or using the platform for any unlawful purpose.' },
      { h: 'Disclaimer', p: 'The emission calculations and reports generated by Carbonless are based on the data you provide and publicly available emission factors. The platform does not guarantee the accuracy of third-party emission factors. Reports are not a substitute for professional verification.' },
      { h: 'Limitation of Liability', p: 'Carbonless shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount paid by you in the twelve months preceding the claim.' },
      { h: 'Modifications', p: 'We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the modified terms.' },
      { h: 'Contact', p: 'For questions about these Terms, please contact us at', email: 'legal@carbonless.info' },
    ],
  },
  tr: {
    title: 'Kullanım Koşulları',
    updated: 'Son güncelleme: Mayıs 2026',
    sections: [
      { h: 'Koşulların Kabulü', p: 'Carbonless platformuna ("Hizmet") erişerek ve kullanarak bu Kullanım Koşulları’na bağlı olmayı kabul edersiniz. Bu koşulları kabul etmiyorsanız lütfen Hizmet’i kullanmayın.' },
      { h: 'Hizmetin Tanımı', p: 'Carbonless, kuruluşların sera gazı emisyonlarını ISO 14064-1:2018 ve GHG Protokolü Kurumsal Standardı’na uygun olarak hesaplamasına, yönetmesine ve raporlamasına yardımcı olan bir karbon envanteri ve raporlama platformudur.' },
      { h: 'Kullanıcı Hesapları', p: 'Hesap bilgilerinizin gizliliğini korumaktan siz sorumlusunuz. Kayıt sırasında doğru ve eksiksiz bilgi vermeyi ve bu bilgileri gerektiğinde güncellemeyi kabul edersiniz.' },
      { h: 'Verilerin Sahipliği', p: 'Platforma girdiğiniz verilerin tüm sahiplik hakları size aittir. Carbonless; emisyon verileriniz, raporlarınız veya Hizmet ile oluşturduğunuz diğer içerikler üzerinde sahiplik iddia etmez.' },
      { h: 'Kabul Edilebilir Kullanım', p: 'Hizmet’i kötüye kullanmamayı kabul edersiniz; bu, yetkisiz erişim girişimini, diğer kullanıcılara müdahaleyi veya platformun hukuka aykırı amaçlarla kullanılmasını kapsar ancak bunlarla sınırlı değildir.' },
      { h: 'Sorumluluk Reddi', p: 'Carbonless’in ürettiği emisyon hesaplamaları ve raporlar, sağladığınız verilere ve kamuya açık emisyon faktörlerine dayanır. Platform, üçüncü taraf emisyon faktörlerinin doğruluğunu garanti etmez. Raporlar profesyonel doğrulamanın yerine geçmez.' },
      { h: 'Sorumluluğun Sınırlandırılması', p: 'Carbonless, Hizmet’i kullanmanızdan doğan dolaylı, arızi veya sonuç olarak ortaya çıkan zararlardan sorumlu tutulamaz. Toplam sorumluluğumuz, talepten önceki on iki ayda ödediğiniz tutarı aşamaz.' },
      { h: 'Değişiklikler', p: 'Bu koşulları istediğimiz zaman değiştirme hakkımız saklıdır. Değişikliklerden sonra Hizmet’i kullanmaya devam etmeniz, değiştirilmiş koşulları kabul ettiğiniz anlamına gelir.' },
      { h: 'İletişim', p: 'Bu Koşullarla ilgili sorularınız için bize yazın:', email: 'legal@carbonless.info' },
    ],
  },
};

export default function TermsPage() {
  return <LegalPage content={CONTENT} />;
}
