# Generated by Django 6.0.3 on 2026-03-11 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity_name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(max_length=100)),
                ('country_of_headquarters', models.CharField(max_length=100)),
                ('countries_of_operation', models.TextField()),
                ('nace_code', models.CharField(blank=True, max_length=50)),
                ('main_activity_description', models.TextField()),
                ('number_of_employees', models.CharField(max_length=50)),
                ('annual_turnover_range', models.CharField(max_length=50)),
                ('number_of_facilities', models.IntegerField()),
                ('has_overseas_operations', models.BooleanField(default=False)),
                ('number_of_subsidiaries', models.IntegerField(default=0)),
                ('has_iso_14001', models.BooleanField(default=False)),
                ('has_iso_50001', models.BooleanField(default=False)),
                ('has_iso_14064_work', models.BooleanField(default=False)),
                ('target_iso_14064_verification', models.BooleanField(default=False)),
                ('has_3rd_party_audit_plan', models.BooleanField(default=False)),
                ('is_for_financing', models.BooleanField(default=False)),
                ('is_due_to_export_pressure', models.BooleanField(default=False)),
                ('is_for_group_reporting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
