# Generated by Django 6.0.3 on 2026-04-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_backfill_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
    ]
