# Generated by Django 5.0.6 on 2026-05-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='annual_turnover_range',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='countries_of_operation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='main_activity_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_employees',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='number_of_facilities',
            field=models.IntegerField(default=0),
        ),
    ]
