# Generated by Django 5.1.15 on 2026-09-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyinvite_expires_at_and_invited_by_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='certificates',
            field=models.TextField(blank=True, help_text='Management-system certificates held, one per line (e.g. ISO 9001:2015 Quality Management Systems)'),
        ),
        migrations.AddField(
            model_name='company',
            name='environmental_regulations',
            field=models.TextField(blank=True, help_text='Environmental regulations the organisation must comply with, one per line'),
        ),
        migrations.AddField(
            model_name='company',
            name='inventory_declaration_scope',
            field=models.TextField(blank=True, help_text='The activities this GHG inventory declaration covers'),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_address',
            field=models.TextField(blank=True, help_text='Registered address of the legal entity'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_office',
            field=models.CharField(blank=True, help_text='Tax office the tax number is registered with', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='trade_registry_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
